<section class="admin__page-section" id="gst-number-content">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Incoterm Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        
        <div id="gst-number">
            <strong><?= __('Incoterm') ?>:</strong>
            <?= $block->getGstNumber() ?>
        </div>
    </div>
</section>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            $('#gst-number-content').insertAfter($('.order-view-billing-shipping'));
        }
    );
</script>