/**
* Product 1
*/

.product-1-style .products-grid .product-item-details .quickview-handler{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-1-style .products-grid .product-item-details .quickview-handler:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-1-style .products-grid .product-item-actions .actions-secondary .action:hover,
.product-1-style .products-grid .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 2
*/

.product-2-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-2-style .products-grid .product-item-info:hover .product-item-actions .actions-primary button{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-2-style .products-grid .product-item-info .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-2-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 3
*/

.product-3-style .products-grid .product-item-actions .actions-secondary .action:hover,
.product-3-style .products-grid .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-3-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 4
*/

.product-4-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-4-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 5
*/

.product-5-style .products-grid .product-item-info:hover .product-item-photo{
border-color: #<?php echo $themeColor; ?>;
}

.product-5-style .products-grid .product-item-info:hover .product-item-actions .actions-primary button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-5-style .products-grid .product-item-info .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-5-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-5-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 6
*/

.product-6-style .products-grid .product-item-info:hover .product-item-actions .actions-primary button,
.product-6-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-6-style .products-grid .product-item-info .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-6-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 7
*/

.product-7-style .products-grid .product-item-info:hover .product-item-actions .actions-primary button,
.product-7-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-7-style .products-grid .product-item-info .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-7-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 8
*/

.product-8-style .products-grid .product-item-actions .actions-secondary .action:hover,
.product-8-style .products-grid .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-8-style .products-grid .image-product .quickview-handler:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-8-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?> !important;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 9
*/

.product-9-style .products-grid .product-item-info:hover{
border-color: #<?php echo $themeColor; ?>;
}

.product-9-style .products-grid .product-item-actions .actions-secondary .action:hover,
.product-9-style .products-grid .product-item-actions .actions-primary button:hover{
background: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-9-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?> !important;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 10
*/

.product-10-style .products-grid .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-10-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-10-style .products-grid .image-product .quickview-handler:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-10-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 11
*/

.product-11-style .products-grid .product-item-info:hover{
border-color: #<?php echo $themeColor; ?>;
}

.product-11-style .products-grid .product-item-info:hover .product-item-actions .actions-primary button,
.product-11-style .products-grid .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-11-style .products-grid .product-item-info .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-11-style .products-grid .product-item .price-box .price{
color: #<?php echo $themeColor; ?>;
}

/**
* Product 12
*/

.product-12-style .products-grid .product-item-info:hover .product-item-actions .actions-primary button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-12-style .products-grid .product-item-info .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

.product-12-style .products-grid .product-item-info .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 13
*/

.product-13-style .products-grid .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-13-style .detail-product-slider .owl-theme .owl-nav [class*='owl-']:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Product 14
*/

.product-14-style .products-grid .product-item-actions .actions-secondary .action:hover,
.product-14-style .products-grid .product-item-actions .actions-primary button:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}
.product-16-style .products-grid .product-labels .sale-label{
	background-color: #<?php echo $themeColor; ?>;
}