<?php
/** @var $block \Magento\Catalog\Block\Product\View */
$callPriceHelper = $this->helper('Darsh\Callforprice\Helper\Data');
$buttonTitle = $callPriceHelper->getButtonTitle();
?>
<?php $_product = $block->getProduct(); ?>
<?php 
$callForPrice = $callPriceHelper->showCallForPriceButton($_product); 
$id = $_product->getId();
$customerData = $callPriceHelper->getCurrentCustomerData();
?>
<!--call for price condition-->
<!-- <?php //echo $callForPrice; die(); ?> -->
<?php if ($callForPrice == 0 || $callPriceHelper->isEnable() == 0) { ?>
    <?php $buttonTitle = __('Add to Cart');
     ?>
    <?php if ($_product->isSaleable()): ?>
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   maxlength="12"
                                   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                                   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                        </div>
                    </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
            "radioCheckboxClosest": ".nested"
            }
            }
            }
        </script>
    <?php else : ?>
        <script>
            require([
                'jquery',
                'mage/mage',
                'Magento_Catalog/product/view/validation',
                'Magento_Catalog/js/catalog-add-to-cart'
            ], function ($) {
                'use strict';

                $('#product_addtocart_form').mage('validation', {
                    radioCheckboxClosest: '.nested',
                    submitHandler: function (form) {
                        var widget = $(form).catalogAddToCart({
                            bindSubmit: false
                        });

                        widget.catalogAddToCart('submitForm', $(form));

                        return false;
                    }
                });
            });
        </script>
    <?php endif; ?>

<?php }else { ?>
    <?php if ($_product->isSaleable()): ?>
        <style>
            .box-tocart .primary.tocart {
                background-color: #FF5500;
                color: #FFFFFF;
                border: 1px solid #FF5500;
                height: 40px;
                padding: 0 25px;
                font-size: 100%;
                text-transform: uppercase;
            }
        </style>
        <div class="add-to-cart box-tocart">
            <button type="button" title="<?php echo $buttonTitle ?>" id="modalRun<?= $id; ?>" class="primary tocart modalRun"><span><span><?php echo $buttonTitle ?></span></span></button>
        </div>

        <div id="popup-modal">

        </div>

        <!-- popup code -->
        <?php
                                    $submitformurl = $callPriceHelper->submitformurl();
                                    ?>
                                        <div id="modal-content" class="<?php echo "modal-content".$id ?>">
                                            <div id="<?php echo "response-message".$id ?>"></div>
                                            <div class="modal-body">
                                                <form name="<?php echo "cp_form".$id ?>" id="<?php echo "cp_form".$id ?>" method="post" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}' data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" >
                                                    <fieldset class="fieldset">
                                                        <div class="field name required">
                                                            <label class="label" for="customer_name"><span><?php echo __("Name"); ?></span></label>
                                                            <div class="control">
                                                                <input name="customer_name" id="<?php echo "customer_name" . $id ?>" title="Name" value="<?php
                                                                if ($customerData) {
                                                                    echo $customerData->getName();
                                                                }

                                                                ?>" class="input-text" type="text" data-validate="{required:true}" />
                                                            </div>
                                                        </div>
                                                        <div class="field email required">
                                                            <label class="label" for="customer_email"><span><?php echo __("Email"); ?></span></label>
                                                            <div class="control">
                                                                <input name="customer_email" id="<?php echo "customer_email" . $id ?>" title="Email" value="<?php
                                                                if ($customerData) {
                                                                    echo $customerData->getEmail();
                                                                }

                                                                ?>" class="input-text" type="text" data-validate="{required:true, 'validate-email':true}" />
                                                            </div>
                                                        </div>
                                                        <div class="field telephone required">
                                                            <label class="label" for="customer_telephone"><span><?php echo __("Telephone"); ?></span></label>
                                                            <div class="control">
                                                                <input name="customer_telephone" id="<?php echo "customer_telephone".$id ?>" title="Telephone" value="" type="text" class="input-text" data-validate="{required:true}" />
                                                            </div>
                                                        </div>
                                                        <div class="field request_detail required">
                                                            <label class="label" for="request_detail"><span><?php echo __("Request Details"); ?></span></label>
                                                            <div class="control">
                                                                <textarea rows="3" cols="5" class="input-text" title="details" id="<?php echo "request_detail".$id ?>" name="request_detail" data-validate="{required:true}"><?php echo "Product Name = ".$_product->getName(); ?></textarea>
                                                            </div>
                                                        </div>
                                                    </fieldset>
                                                    <input type="hidden" name="status" id="<?php echo "status".$id ?>" value="1"/>
                                                    <input type="hidden" name="product_name" id="<?php echo "product_name".$id ?>" value="<?php echo $_product->getName(); ?>"/>
                                                    <input type="hidden" name="product_id" id="<?php echo "product_id".$id ?>" value="<?php echo $_product->getEntityId(); ?>"/>
                                                    <input type="hidden" name="customer_id" id="<?php echo "customer_id".$id ?>" value="<?php echo $_product->getEntityId(); ?>"/>
                                                </form>
                                            </div>
                                        </div>
                                        <script>
                                            require(
                                                [
                                                    'jquery',
                                                    'Magento_Ui/js/modal/modal'
                                                ],
                                                function($,modal) {
                                                    $('#modal-content').modal({
                                                        type: 'popup',
                                                        responsive: true,
                                                        innerScroll: true,
                                                        title: "Submit Form For Price",
                                                        buttons: [{
                                                            text: $.mage.__('Submit'),
                                                            class: 'action  primary',
                                                            click: function (data) {
                                                                var dataForm = $('#cp_form' +<?php echo $id; ?>);
                                                                if (dataForm.validation('isValid')) {
                                                                    var customer_name = $("#customer_name" +<?php echo $id; ?>).val();
                                                                    var customer_email = $("#customer_email" +<?php echo $id; ?>).val();
                                                                    var customer_telephone = $("#customer_telephone" +<?php echo $id; ?>).val();
                                                                    var request_detail = $("#request_detail" +<?php echo $id; ?>).val();
                                                                    var product_id = $("#product_id" +<?php echo $id; ?>).val();
                                                                    var customer_id = $("#customer_id" +<?php echo $id; ?>).val();
                                                                    var status = $("#status" +<?php echo $id; ?>).val();
                                                                    var product_name = $("#product_name" +<?php echo $id; ?>).val();
                                                                    if(customer_name && customer_email && customer_telephone && request_detail && product_id && customer_id && status && product_name){
                                                                        $.ajax({
                                                                            url: "<?php echo $submitformurl; ?>",
                                                                            dataType: 'json',
                                                                            type: 'POST',
                                                                            showLoader: true,
                                                                            data: {customer_name: customer_name, customer_email: customer_email, customer_telephone: customer_telephone, request_detail: request_detail, product_id: product_id, customer_id: customer_id, status: status, product_name: product_name},
                                                                            success: function (data) {
                                                                                if (data.status == "success") {
                                                                                    $("#cp_form" +<?php echo $id; ?>).trigger("reset");
                                                                                    $("#response-message" +<?php echo $id; ?>).addClass("success");
                                                                                    $("#response-message" +<?php echo $id; ?>).html(data.message);
                                                                                } else {
                                                                                    $("#response-message" +<?php echo $id; ?>).addClass("error");
                                                                                    $("#response-message" +<?php echo $id; ?>).html(data.message);
                                                                                }
                                                                            }
                                                                        });
                                                                    }
                                                                }
                                                            }
                                                        }]
                                                    });
                                                    $("#modalRun" +<?php echo $id; ?>).on("click",function(){
                                                        $("#cp_form" +<?php echo $id; ?>).trigger("reset");
                                                        $("#response-message" +<?php echo $id; ?>).html("");
                                                        $("#response-message" +<?php echo $id; ?>).removeClass("success");
                                                        $("#response-message" +<?php echo $id; ?>).removeClass("error");
                                                        $('.modal-content' +<?php echo $id; ?>).modal('openModal');

                                                    });
                                                    $('.modal-popup').wrap('<div class="call-for-price"></div>')
                                                });

                                        </script>
                                        <!-- popup code end-->

    <?php endif; ?>

<?php } ?>
